version: '3.9'
services:
  eureka-server:
    build: '../eureka-server'
    ports: 
      - '8761:8761'
  rest-app:
    build: .
    depends_on:
      - eureka-server
    ports: 
      - '8081:8080'
    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka
      - SERVER_PORT=8080
  rest-app-b:
    build: '../docker-microservice-b'
    depends_on:
      - eureka-server
    ports: 
      - '8080' # Te permite que puedas hacer SCALLING de rest-app-b, selecciona un random port host y lo mapea al puerto 8080 del container
    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka
      - SERVER_PORT=8080
