version: '3.9'
services:

  eureka-server:
    build: '../eureka-server'
    expose:     # expose te permite indicarle que puerto abrir del container pero solo va a ser accesible dentro del la misma network que esten los container (es decir no es accesible por el host
      - '8761'

  rest-app:
    build: .
    expose:     # expose te permite indicarle que puerto abrir del container pero solo va a ser accesible dentro del la misma network que esten los container (es decir no es accesible por el host)
      - '8080'
    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka
      - SERVER_PORT=8080
    volumes:
      C:/mi_volumen:/app
    depends_on:
      - eureka-server

  rest-app-b:
    build: '../docker-microservice-b'
    expose:     # expose te permite indicarle que puerto abrir del container pero solo va a ser accesible dentro del la misma network que esten los container (es decir no es accesible por el host)
      - '8080'  
    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka
      - SERVER_PORT=8080
    depends_on:
      - eureka-server

  nginx:
    image: nginx:alpine-slim
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports: 
      - '80:80' # port ademas de abrir el puerto del container dentro de la misma network (idem al funcionamiento de expose), ademas te permite acceder desde afuera de la network especifamente desde el host (mediante localhost)
    depends_on:
      - rest-app
      - rest-app-b
